import type { FontMetadata } from './types.ts';

export const ACADEMIC_FONT_INVENTORY: Record<string, FontMetadata> = {

  stixTwoText: {
    family: 'STIX Two Text',
    files: [
      'STIXTwoText-Regular.otf',
      'STIXTwoText-Bold.otf',
      'STIXTwoText-Italic.otf',
      'STIXTwoText-BoldItalic.otf',
    ],
    license: 'OFL-1.1',
    licenseUrl: 'https://scripts.sil.org/OFL',
    sourceUrl: 'https://github.com/stipub/stixfonts',
    version: '2.13',
    languageSupport: ['en', 'symbol'],
    mathSupport: false,
    redistributionAllowed: true,
    bundledInTexLive: true,
    recommendedFallback: 'Latin Modern Roman',
  },
  stixTwoMath: {
    family: 'STIX Two Math',
    files: ['STIXTwoMath-Regular.otf'],
    license: 'OFL-1.1',
    licenseUrl: 'https://scripts.sil.org/OFL',
    sourceUrl: 'https://github.com/stipub/stixfonts',
    version: '2.13',
    languageSupport: ['math', 'symbol'],
    mathSupport: true,
    redistributionAllowed: true,
    bundledInTexLive: true,
    recommendedFallback: 'latinmodern-math.otf',
  },

  sourceHanSerif: {
    family: 'Source Han Serif SC',
    files: [
      'SourceHanSerifSC-Regular.otf',
      'SourceHanSerifSC-Bold.otf',
      'NotoSerifSC-Regular.otf',
      'NotoSerifCJKsc-Regular.otf',
      'NotoSerifSC-VF.ttf',
    ],
    license: 'OFL-1.1',
    licenseUrl: 'https://scripts.sil.org/OFL',
    sourceUrl: 'https://github.com/adobe-fonts/source-han-serif',
    version: '2.002',
    languageSupport: ['zh-CN', 'en', 'symbol'],
    mathSupport: false,
    redistributionAllowed: true,
    bundledInTexLive: false,
    recommendedFallback: 'FandolSong-Regular.otf',
  },

  sourceHanSans: {
    family: 'Source Han Sans SC',
    files: [
      'SourceHanSansSC-Regular.otf',
      'SourceHanSansSC-Bold.otf',
      'NotoSansSC-Regular.otf',
      'NotoSansCJKsc-Regular.otf',
      'NotoSansSC-VF.ttf',
    ],
    license: 'OFL-1.1',
    licenseUrl: 'https://scripts.sil.org/OFL',
    sourceUrl: 'https://github.com/adobe-fonts/source-han-sans',
    version: '2.004',
    languageSupport: ['zh-CN', 'en', 'symbol'],
    mathSupport: false,
    redistributionAllowed: true,
    bundledInTexLive: false,
    recommendedFallback: 'FandolHei-Regular.otf',
  },

  fandolSong: {
    family: 'FandolSong',
    files: ['FandolSong-Regular.otf', 'FandolSong-Bold.otf'],
    license: 'GPLv3-with-font-exception',
    licenseUrl: 'https://www.gnu.org/licenses/gpl-3.0.html',
    sourceUrl: 'https://ctan.org/pkg/fandol',
    version: '0.32',
    languageSupport: ['zh-CN', 'symbol'],
    mathSupport: false,
    redistributionAllowed: true,
    bundledInTexLive: true,
  },
  fandolHei: {
    family: 'FandolHei',
    files: ['FandolHei-Regular.otf', 'FandolHei-Bold.otf'],
    license: 'GPLv3-with-font-exception',
    licenseUrl: 'https://www.gnu.org/licenses/gpl-3.0.html',
    sourceUrl: 'https://ctan.org/pkg/fandol',
    version: '0.32',
    languageSupport: ['zh-CN', 'symbol'],
    mathSupport: false,
    redistributionAllowed: true,
    bundledInTexLive: true,
  },
  fandolKai: {
    family: 'FandolKai',
    files: ['FandolKai-Regular.otf'],
    license: 'GPLv3-with-font-exception',
    licenseUrl: 'https://www.gnu.org/licenses/gpl-3.0.html',
    sourceUrl: 'https://ctan.org/pkg/fandol',
    version: '0.32',
    languageSupport: ['zh-CN', 'symbol'],
    mathSupport: false,
    redistributionAllowed: true,
    bundledInTexLive: true,
  },

  latinModernRoman: {
    family: 'Latin Modern Roman',
    files: [
      'lmroman10-regular.otf',
      'lmroman10-bold.otf',
      'lmroman10-italic.otf',
      'lmroman10-bolditalic.otf',
    ],
    license: 'GFL',
    licenseUrl: 'http://www.gust.org.pl/projects/e-foundry/licenses',
    sourceUrl: 'https://ctan.org/pkg/lm',
    version: '2.004',
    languageSupport: ['en', 'symbol'],
    mathSupport: false,
    redistributionAllowed: true,
    bundledInTexLive: true,
  },
  latinModernMath: {
    family: 'Latin Modern Math',
    files: ['latinmodern-math.otf'],
    license: 'GFL',
    licenseUrl: 'http://www.gust.org.pl/projects/e-foundry/licenses',
    sourceUrl: 'https://ctan.org/pkg/lm-math',
    version: '1.959',
    languageSupport: ['math', 'symbol'],
    mathSupport: true,
    redistributionAllowed: true,
    bundledInTexLive: true,
  },

  libertinusSerif: {
    family: 'Libertinus Serif',
    files: [
      'LibertinusSerif-Regular.otf',
      'LibertinusSerif-Bold.otf',
      'LibertinusSerif-Italic.otf',
      'LibertinusSerif-BoldItalic.otf',
    ],
    license: 'OFL-1.1',
    licenseUrl: 'https://scripts.sil.org/OFL',
    sourceUrl: 'https://github.com/alerque/libertinus',
    version: '7.040',
    languageSupport: ['en', 'symbol'],
    mathSupport: false,
    redistributionAllowed: true,
    bundledInTexLive: true,
    recommendedFallback: 'STIX Two Text',
  },
  libertinusMath: {
    family: 'Libertinus Math',
    files: ['LibertinusMath-Regular.otf'],
    license: 'OFL-1.1',
    licenseUrl: 'https://scripts.sil.org/OFL',
    sourceUrl: 'https://github.com/alerque/libertinus',
    version: '7.040',
    languageSupport: ['math', 'symbol'],
    mathSupport: true,
    redistributionAllowed: true,
    bundledInTexLive: true,
    recommendedFallback: 'STIXTwoMath-Regular.otf',
  },

  lxgwWenKai: {
    family: 'LXGW WenKai GB',
    files: [
      'LXGWWenKaiGBLite-Regular.ttf',
      'LXGWWenKaiGBLite-Bold.ttf',
      'LXGWWenKai-Regular.ttf',
    ],
    license: 'OFL-1.1',
    licenseUrl: 'https://scripts.sil.org/OFL',
    sourceUrl: 'https://github.com/lxgw/LxgwWenKai',
    version: '1.330',
    languageSupport: ['zh-CN', 'en', 'symbol'],
    mathSupport: false,
    redistributionAllowed: true,
    bundledInTexLive: true,
    recommendedFallback: 'FandolKai-Regular.otf',
  },

  newComputerModernMath: {
    family: 'NewCMMath-Book',
    files: ['NewCMMath-Book.otf', 'NewCMMath-Regular.otf'],
    license: 'GFL',
    licenseUrl: 'http://www.gust.org.pl/projects/e-foundry/licenses',
    sourceUrl: 'https://ctan.org/pkg/newcomputermodern',
    version: '4.7',
    languageSupport: ['math', 'symbol'],
    mathSupport: true,
    redistributionAllowed: true,
    bundledInTexLive: true,
    recommendedFallback: 'latinmodern-math.otf',
  },
};
